### ISSUE TITLE
smaller layout?

### ISSUE THREAD

**Issue by GoodWillGustin** [lavolp3/MMM-AVStock#14]
Is it possible to have the 'ticker' style (name, price, amt change) in a static view like table or series? I want this to take up less space, meaning that I will only have a few stocks and want them to stack vertically with the minimal info.  (Having only 3 stocks scrolling by on a ticker looks silly on my MM.)

**Comment by eouia** [comment]
In Tabel View;
You can hide column by modifying `css/custom.css` like this.
```CSS
#AVSTOCK_TABLE .changeP{
  display:none;
}
```
It will hide `CHG%` column.
All the selectors of columns are these;
`symbol`, `price`, `close`, `change`, `changeP`, `volume`.

If you want to adjust size; It could be done also with CSS

```css

#AVSTOCK_TABLE {
  width: 250px;
  font-size: 12px;
}
```
